### ISSUE TITLE
env issue with python docker image

### ISSUE THREAD

**Issue by petreeftime** [aws/aws-nitro-enclaves-cli#188]
Based on https://levelup.gitconnected.com/running-python-app-on-aws-nitro-enclaves-56024667b684, the docker python image does not start under an enclave. Investigate why this is happening:

> For Python app development, using Python base image would be an obvious step. But for some reason, the python image is not running properly in the Nitro Enclave.
> No matter I use the standard image, -slim image or -alpine image, even my Dockerfile is just running a simple echo command, an error Could not open /env file: No such file or directory will come up.

**Comment by bercarug** [comment]
Solved by https://github.com/aws/aws-nitro-enclaves-cli/pull/198
