### ISSUE TITLE
nitro-enclaves-allocator: get_enclave_cpus not defined

### ISSUE THREAD

**Issue by jethrogb** [aws/aws-nitro-enclaves-cli#192]
When specifying a CPU pool instead of count in `/etc/nitro_enclaves/allocator.yaml`, I get the following error when starting nitro-enclave-allocator:

```
Nov 05 14:40:30 ip-172-31-24-166.ec2.internal nitro-enclaves-allocator[8407]: /usr/bin/nitro-enclaves-allocator: line 152: get_enclave_cpus: command not found
```

Also, specifying a count instead of a pool doesn't work properly if there are currently offline CPUs.

**Comment by axlprv** [comment]
Hi @jethrogb,

I've defined the `get_enclave_cpus` function in `nitro-enclaves-allocator` (PR #202). The issue regarding the offline CPUs is fixed by @bercarug in PR #201.
