### ISSUE TITLE
Segfault in init

### ISSUE THREAD

**Issue by jethrogb** [aws/aws-nitro-enclaves-cli#194]
```
Could not open /env file: No such file or directory
Could not open /env file: No such file or directory
[    0.793543] init[1]: segfault at 0 ip 0000000000410e84 sp 00007fff27e27340 error 4 in init[400000+d4000]
```

The IP corresponds to fclose. You can't call fclose(NULL).

**Comment by jethrogb** [comment]
This happens if you set `ENTRYPOINT` but not `ENV` or `CMD` in your Dockerfile.

**Comment by alexggh** [comment]
> This happens if you set ENTRYPOINT but not ENV or CMD in your Dockerfile.

@jethrogb: I think you just helped us debug this: https://github.com/aws/aws-nitro-enclaves-cli/issues/188
Thank you

**Comment by jethrogb** [comment]
> This happens if you set ENTRYPOINT but not ENV or CMD in your Dockerfile.

Not yet convinced this is the whole story.

**Comment by jethrogb** [comment]
Are there supposed to be two EifSectionRamdisk sections in the Eif?

**Comment by jethrogb** [comment]
I think there's some issue with initrd concatenation.

**Comment by jethrogb** [comment]
This works:
```
# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

FROM busybox

RUN truncate -s $((300*1024*1024)) /large_file

ENV HELLO="Hello from the enclave side!"

CMD ["/bin/sh", "-c", "while true; do echo \"$HELLO\"; sleep 10; done"]
```
This doesn't:
```
# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

FROM busybox

RUN truncate -s $((350*1024*1024)) /large_file

ENV HELLO="Hello from the enclave side!"

CMD ["/bin/sh", "-c", "while true; do echo \"$HELLO\"; sleep 10; done"]
```

**Comment by alexggh** [comment]
@jethrogb: You pointed to the exact error, the problem is the following you allocated to the enclave less memory than the linux kernel needs to unpack the ramfs. 

If you look at the kernel logs with the console command you would probably first see "Failed to unpack initiramfs"

As of now the guideline is that the enclave should have allocated at least 4 times more memory than the size of the EIF.

**Comment by jethrogb** [comment]
Indeed it says:
```
[    0.268206] Unpacking initramfs...
[    0.586559] Initramfs unpacking failed: write error
```

But that happens in the middle of a lot of other kernel messages, so yes some more diagnostics around this would be helpful.

**Comment by bercarug** [comment]
Solved by https://github.com/aws/aws-nitro-enclaves-cli/pull/198
