### ISSUE TITLE
Is blobs/linuxkit docker's linuxkit?

### ISSUE THREAD

**Issue by asim** [aws/aws-nitro-enclaves-cli#199]
Where has linuxkit been derived from in this repo? If this belongs to Docker should credit be provided back to them for the authoring of that code e.g licensing requirements.

**Comment by neacsu** [comment]
Hey,

Thanks for pointing this out. I added third_party directory that contains a reference to the linuxkit repo, along with its license. We can use this for future third party usages.

Bogdan
