### ISSUE TITLE
Fail to  read "/root/.aws/config"

### ISSUE THREAD

**Issue by li-xin-yi** [aws/aws-nitro-enclaves-cli#212]
I launched a bare AWS Nitro image from AWS and fully followed the document. But I got stuck when I tried 

```
docker run --network host -it kmstool-instance \
    /kmstool_instance --cid "$ENCLAVE_CID" "$CIPHERTEXT"
```

I got the error message

```

[ERROR] [2020-12-17T12:07:35Z] [00007f76c19d7880] [file-utils] - static: Failed to open file /root/.aws/config with errno 2
[WARN] [2020-12-17T12:07:35Z] [00007f76c19d7880] [AuthProfile] - Failed to read file at "/root/.aws/config"
[DEBUG] [2020-12-17T12:07:35Z] [00007f76c19d7880] [AuthProfile] - Creating profile collection from file at "/root/.aws/credentials"
[ERROR] [2020-12-17T12:07:35Z] [00007f76c19d7880] [file-utils] - static: Failed to open file /root/.aws/credentials with errno 2
[WARN] [2020-12-17T12:07:35Z] [00007f76c19d7880] [AuthProfile] - Failed to read file at "/root/.aws/credentials"
[ERROR] [2020-12-17T12:07:35Z] [00007f76c19d7880] [AuthCredentialsProvider] - static: Profile credentials parser could not load or parse a credentials or config file.
...
```

I wonder why it must get credentials from `root` folder. Should it run with root privilege? Why not leave the interface out to get credentials from the user? 

And how can I resolve it now?

**Comment by petreeftime** [comment]
The docker container for `kmstool-instance` uses the root user by default in it's respective container namespace, so it will look in the root home of that container for credentials (and will likely never find anything there), not of the host. `kmstool-instance` doesn't really need to run as root, but in this case `kmstool-instance` is the only application that it should be running in the container, so it doesn't affect security of container or host.

This is not really an error though. The way credential resolution works is that it will check a series of credential providers, among which is also the aws configuration file found in `$HOME/.aws/config` or `$HOME/.aws/credentials`, until it finds a valid credential. We mostly expect these credentials to come from the instance IMDS, but I'm not 100% of the order in which it checks. I think the order is environment variables, configuration files and then IMDS, so even when this operation succeeds, it will end up logging that it didn't find any credentials on the file system.

If you are having issues with this behavior, it's possible that your instance doesn't have a role attached, so `kmstool-instance` can't get any role to use. It's also possible to specify this behavior by passing the IAM role as environment variables to the container when starting it, or, by setting them up in `$HOME/.aws/config` in the container (although I would not recommend this second approach for anything except testing).
