### ISSUE TITLE
The error documentation hosts `enclaves.aws.amazon.com` does not seem to exist

### ISSUE THREAD

**Issue by spkane** [aws/aws-nitro-enclaves-cli#217]
`nitro-cli` generates errors that direct users to `For more details, please visit http://enclaves.aws.amazon.com/nitro-cli/`, but the host does not seem to be publicly accessible.

```shell
$  nitro-cli run-enclave --cpu-count 1 --memory 256 --eif-path hello.eif --debug-mode

[ E19 ] File operation failure. Such error appears when the system fails to perform the requested file operations, such as opening the EIF file when launching an enclave, or seeking to a specific offset in the EIF file, or writing to the log file.

For more details, please visit http://enclaves.aws.amazon.com/nitro-cli/errors#E19

If you open a support ticket, please provide the error log found at "/var/log/nitro_enclaves/err2021-01-18T22:22:46.900607914+00:00.log"
Failed connections: 1
[ E39 ] Enclave process connection failure. Such error appears when the enclave manager fails to connect to at least one enclave process for retrieving the description information.

For more details, please visit http://enclaves.aws.amazon.com/nitro-cli/errors#E39

If you open a support ticket, please provide the error log found at "/var/log/nitro_enclaves/err2021-01-18T22:22:46.901092465+00:00.log"
```

**Comment by andraprs** [comment]
That's the actual webpage where the nitro-cli errors info is included: https://docs.aws.amazon.com/enclaves/latest/user/cli-errors.html.

There is a fix already merged in the GitHub repo: https://github.com/aws/aws-nitro-enclaves-cli/commit/ab4e03bc37fc7fcf6f98c42d416612976299989a. The next step will be to have a new release of the aws-nitro-enclaves-cli RPM available in the Amazon Linux extras repo, including this fix as well.

**Comment by andraprs** [comment]
A new release of the aws-nitro-enclaves-cli RPM is available in the Amazon Linux 2 extras repo.

```
$ yum list aws-nitro-enclaves-cli
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Available Packages
aws-nitro-enclaves-cli.x86_64                      1.0.10-1.amzn2                      amzn2extra-aws-nitro-enclaves-cli
```

**Comment by gkarc** [comment]
This issue still exists , how this get works ?

**Comment by gkarc** [comment]
@andraprs  When is this fix getting released? Facing teh issue in 
```[ec2-user@ip-172-30-1-111 ~]$ yum list aws-nitro-enclaves-cli
Loaded plugins: dkms-build-requires, extras_suggestions, langpacks, priorities, update-motd
Installed Packages
aws-nitro-enclaves-cli.x86_64   
```

**Comment by andraprs** [comment]
The fix was released starting with the RPM version mentioned before - 1.0.10-1.amzn2. The issue was that the documentation link for errors was not correct. The fix was to change the documentation link from "http://enclaves.aws.amazon.com/nitro-cli/errors" to "https://docs.aws.amazon.com/enclaves/latest/user/cli-errors.html".
