### ISSUE TITLE
`udevadm trigger -y nitro_enclaves` does not appear to apply udev rules properly when run from userdata during node provisioning

### ISSUE THREAD

**Issue by spkane** [aws/aws-nitro-enclaves-cli#227]
I am adding Nitro enclave nodes to my EKS cluster and overall it is working well, but I do have an issue that I have had to work around.

I am spinning up an EKS cluster using:
* **AMI**: amazon-eks-node-1.18-v20210125
  * from: https://github.com/awslabs/amazon-eks-ami/releases
* **Instance Type**: i3en.xlarge
* **Region**: us-west2

I have one node that is Enclave Enabled and in the userdata for that node I have the following steps (among others):

```shell
amazon-linux-extras install aws-nitro-enclaves-cli -y
yum install aws-nitro-enclaves-cli-devel -y
usermod -aG ne ec2-user
usermod -aG docker ec2-user
systemctl start nitro-enclaves-allocator.service && systemctl enable nitro-enclaves-allocator.service
systemctl start docker  && systemctl enable docker
```

When the system is done provisioning, if I login as `ec2-user`, I am unable to run an enclave, unless I reboot the node first.

After some help from @andraprs, we determined that the issue appears to be related to:
https://github.com/aws/aws-nitro-enclaves-cli/blob/main/SPECS/aws-nitro-enclaves-cli.spec#L114

From what I can tell this line doesn't do anything in this scenario. Maybe because services are still starting?

The initial fix I discovered was to simply add `chgrp ne /dev/nitro_enclaves` to the bottom of my userdata script.

Running `udevadm trigger -y nitro_enclaves` from the RPM with an additional readiness and success check might help here.

@andraprs and I have more detailed logs, etc, but I think that this should cover the important details.

**Comment by andraprs** [comment]
https://github.com/openebs/openebs/issues/2814#issuecomment-603709862

"The udev rules should be configured at the boot time before the worker nodes join the cluster. This can be achieved by adding a user-data script that is executed at the boot time."

May be an option to have several commands run during boot time e.g. user setup, package install.

https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html#launch-template-user-data

https://cloudinit.readthedocs.io/en/latest/topics/examples.html

**Comment by spkane** [comment]
Until a proper fix is found, the spec file could in theory also use the workaround I mentioned above  (`chgrp ne /dev/nitro_enclaves`) before trying to reload the udev rules, assuming that this is the expected result in all cases. That would at least ensure that the group is correct even if the udev trigger doesn't work before a full system reboot.
