### ISSUE TITLE
Feature: Add the capability to disconnect from the console after a set time

### ISSUE THREAD

**Issue by spkane** [aws/aws-nitro-enclaves-cli#229]
There are times (in scripts, etc) that I would really like to run something like this:

`nitro-cli console --enclave-id i-0ee2fsdfdsfdsfdsdf47cce-enc177b7b7sdfsdfdsfdsfs --disconnect 10s`

So, that I can get some output from the console, analyze it and then move on to the next step.

**Comment by petreeftime** [comment]
The usual method to do something like this would be `timeout 10s nitro-cli console --enclave-id i-0ee2fsdfdsfdsfdsdf47cce-enc177b7b7sdfsdfdsfdsfs`. Is there an advantage to integrating this directly into the `console` command itself?

**Comment by spkane** [comment]
That would likely work as long a the tool is available. I was thinking about a container situation, so it might not necessarily be there, but it is an option.
