### ISSUE TITLE
Increase enclave disk space

### ISSUE THREAD

**Issue by mdamgaard-biolib** [aws/aws-nitro-enclaves-cli#241]
When starting enclaves on my ec2 machine (m5.2xlarge) i noticed that the enclave always has 4.03GB of disk space, which is not enough for my code and the data i want to handle.

Output of `df` run inside an enclave only containing the latest `ubuntu`:

```
Filesystem     1K-blocks   Used Available Use% Mounted on
dev              4031892      0   4031892   0% /dev
tmpfs            4083476      0   4083476   0% /run
tmpfs            4083476      0   4083476   0% /tmp
shm              4083476      0   4083476   0% /dev/shm
cgroup_root      4083476      0   4083476   0% /sys/fs/cgroup
```

Is there any way to increase the amount of disk space allocated to the enclave?

**Comment by mdamgaard-biolib** [comment]
Through some experimenting it seems to me that it scales with the amount of RAM provisioned to the Enclave. More specifically the disk space seems to be half the amount of RAM provisioned.

Is the filesystem virtual and therefore contained in memory?
Or am i completely wrong here? 😅

**Comment by petreeftime** [comment]
That is correct. Nitro Enclaves don't have a access to a physical disk, just a RAM file system. This can be configured by changing memory size and by providing kernel command line parameters.

**Comment by mdamgaard-biolib** [comment]
Alright, that does makes great sense for an Enclave.
Does that mean it reserves half of the provisioned RAM, at startup, for the file system or does it use only what it needs of the provisioned RAM as the file system grows?

**Comment by petreeftime** [comment]
A part of this behaviour is driven by init.c: https://github.com/aws/aws-nitro-enclaves-cli/blob/main/init.c#L110-L133, in particular, you can increase the space allocated to `/tmp` or `/run`. For example:
```
{ OpMount, .mount = { "tmpfs", "/tmp", "tmpfs", MS_NODEV | MS_NOSUID | MS_NOEXEC, "size=100%" } },
```
Please note that 100% is the maximum allocated size, and not what is actually being used, it only uses what it needs. This can be recompiled using `make init` target and moved to `/usr/share/nitro_enclaves/blobs/init`.

The root volume itself should be set up using `rootflags` kernel commandline parameter in a similar way. However, it doesn't seem to behave the way I expected it to and I need to do a bit more research on why that is.

**Comment by mdamgaard-biolib** [comment]
@petreeftime
Thanks!

The current behaviour should be fine for me now that i know i can just scale by running larger machines.

I would consider this issue pretty complete for people searching in the future so unless there is more relevant and related info, then you can go ahead and close 😄

**Comment by petreeftime** [comment]
This behavior should be better documented, so I'll keep this issue open until then.
