### ISSUE TITLE
vsock_proxy packaged with release v0.1.0 is buggy

### ISSUE THREAD

**Issue by ppmag** [aws/aws-nitro-enclaves-cli#248]
It would be great to see next release soon, since vsock_proxy packaged with release v0.1.0
has bugs related to YAML allowlist parsing (it panics even with test config located in subdir).

vsock_proxy from main branch just works.

**Comment by petreeftime** [comment]
Our AL2 RPMs are at version 1.0, but it seems there are no equivalent github releases for them.

**Comment by petreeftime** [comment]
I've added Release and tag v1.0.10 to reflect the current AL2 release.
