### ISSUE TITLE
Assigning vGPU to Enclaves

### ISSUE THREAD

**Issue by jkfitzsimons** [aws/aws-nitro-enclaves-cli#252]
I've been using nitro-cli extensively, so thank you! 

However, currently, when we `nitro-cli run-enclave` we can define the vCPUs and RAM to assign to the enclave. There currently seems to be no way of assigning GPU resources. Is this in the roadmap? If not is there a workaround that you could suggest?

**Comment by mdamgaard-biolib** [comment]
+1 on this.

It would be immensely helpful as the enclaves are perfect tools for analysing sensitive data.

This data analysis and machine learning scales a lot better on GPUs.
If GPUs are not available in the enclaves, is there access to the Inferentia chips on the Inf1?

**Comment by petreeftime** [comment]
Currently it's not possible to attach any PCI devices (GPUs, Inf1) to the enclave.

**Comment by mdamgaard-biolib** [comment]
Is it on the roadmap or have you looked into the scale of implementing it? 

I can imagine that it will be a highly requested feature as users want to scale their data analysis in the enclaves.
Do you have any feature request pipeline or is this issue enough?

**Comment by jkfitzsimons** [comment]
> Currently it's not possible to attach any PCI devices (GPUs, Inf1) to the enclave.

That's super helpful to know! I had assumed this resource separation was already managed by the hypervisor for multi-tenant usage thus possible to integrate to nitro. Thanks for the clarification.

**Comment by LorenzoTomaz** [comment]
any recent updates about this?
