### ISSUE TITLE
Kernel version mismatch between repositories

### ISSUE THREAD

**Issue by dimalinux** [aws/aws-nitro-enclaves-cli#257]
The bzImage in this repo (https://github.com/aws/aws-nitro-enclaves-cli/blob/main/blobs/x86_64/bzImage) is reporting `4.14.177` when you boot it, but the repository used to build the image is showing `4.14.204`: https://github.com/aws/aws-nitro-enclaves-sdk-bootstrap/blob/main/linux-url

Does the image in this repo require updates?  Or should the other repo be providing links for the 4.14.177 source code?

**Comment by andraprs** [comment]
The bzImage from the Nitro Enclaves CLI repo (https://github.com/aws/aws-nitro-enclaves-cli/blob/main/blobs/x86_64/bzImage) is based on the v4.14 Amazon Linux kernel (https://github.com/amazonlinux/linux/tree/amazon-4.14.y/master).

The kernel mentioned in https://github.com/aws/aws-nitro-enclaves-sdk-bootstrap/blob/main/linux-url is an example that can be used for building an enclave image. It is different than the one in the Nitro Enclaves CLI repo.

Created a set of PRs to include info about the kernel references.
