### ISSUE TITLE
Early kernel boot debugging?

### ISSUE THREAD

**Issue by exFalso** [aws/aws-nitro-enclaves-cli#343]
Hi, we would like to use a custom built kernel for our enclaves, however we're bumping into issues during boot, it seems `init` doesn't reach the `enclave_ready()` call, and the nitro-cli `run-enclave` doesn't return as it does for enclaves built with the official kernel. Consequently we cannot even attach the console to the enclave to look at kernel logs.

One of the reasons we'd like to use our own kernel is to strip down the kernel config, and most probably our kernel is too minimal at this point for nitro usage. We have tested our kernel+initrd with qemu and it works well, so there must be something nitro-specific that's failing (we have configured MMIO-based virtio as well).

We are unsure how to proceed with the debugging, aside from slowly enabling all kernel features that the official nitro kernel has (although we're using a 5.16 kernel, so there are some inherent differences). Is there any way we can attach to the serial without the nitro-cli `console` invocation so we can see kernel messages before the `enclave_ready()` heartbeat?

I have attached our kernel config just in case (this is not the fully stripped down version, contains debugging features): [config.txt](https://github.com/aws/aws-nitro-enclaves-cli/files/7965868/config.txt)

**Comment by petreeftime** [comment]
For early boot debugging, we recently merged https://github.com/aws/aws-nitro-enclaves-cli/pull/340, although it's not released yet as part of the aws-nitro-enclaves-cli package.

**Comment by exFalso** [comment]
> For early boot debugging, we recently merged #340, although it's not released yet as part of the aws-nitro-enclaves-cli package.

Thank you, this seems useful in general, however this also requires the guest to ping CID 3 before the attach, the `EnclaveRunInfo` is not returned before that. The failure we're trying to debug happens before this call:
https://github.com/aws/aws-nitro-enclaves-sdk-bootstrap/blob/746ec5d2713e539b94e651601b5c24ec1247c955/init/init.c#L410

**Comment by petreeftime** [comment]
Ah, I misunderstood the issue slightly. Yes, it's currently possible to do early-boot debugging, but it requires an external program:

I use the following `console.py` program:
```
#!/usr/bin/env python3

import os
import socket
import sys

cid = int(os.environ['ENCLAVE_CID'])
s = socket.socket(socket.AF_VSOCK, socket.SOCK_STREAM)
s.connect((0, 10000 + cid))

while True:
    cons_out = s.recv(256)
    if len(cons_out) == 0:
        break
    sys.stdout.buffer.write(cons_out)
    sys.stdout.buffer.flush()

s.close()
```

The I just run in one terminal:
```
nitro-cli run-enclave --eif-path /tmp/hello.eif --debug-mode --cpu-count 2 --memory 256 --enclave-cid 42
```

And in another:
```
ENCLAVE_CID=42 ./console.py
```

**Comment by exFalso** [comment]
Thank you, this looks nice! However I'm getting a timeout on the vsock connection, I think the kernel is just crashing too early..

On the bright side, with `make oldconfig` I managed to make the VM work with a custom build kernel using the blobs/ bzImage.config options, so now it's just a matter of figuring out which options were missing for a correct boot. I'll post the config here when I figure it out in case someone needs it

**Comment by exFalso** [comment]
The missing config option was `CONFIG_VIRTIO_MMIO_CMDLINE_DEVICES`. So to fully enable nitro-compatible vsock virtio:
```
      ./scripts/config --enable CONFIG_VIRTIO_MMIO
      ./scripts/config --enable CONFIG_VIRTIO_MENU
      ./scripts/config --enable CONFIG_VIRTIO_MMIO_CMDLINE_DEVICES
      ./scripts/config --enable CONFIG_NET
      ./scripts/config --enable CONFIG_VSOCKETS
      ./scripts/config --enable CONFIG_VIRTIO_VSOCKETS
```
We're still bumping into an issue with the initramfs (a mysterious compression error which doesn't appear in QEMU), but the console is now working! Here's the [config.txt](https://github.com/aws/aws-nitro-enclaves-cli/files/7971923/config.txt)

Thank you!

**Comment by petreeftime** [comment]
How does the compression error manifest?

**Comment by petreeftime** [comment]
It's possible that there's not enough memory space to decompress the second initramfs image. The first one, containing just the init and configuration files is very tiny.

**Comment by exFalso** [comment]
The custom build is actually smaller than the one using bzImage.config (the small one uses ~half of the kernel options, making the kernel several MB smaller), the initramfs is the same size (~260M), and the VM is started with 8G RAM. So I don't think it's a memory issue. But anyway, all this is speculation, I'll return to this when we have more time to debug. The original issue with the kernel logging is solved so I'll close the ticket, I'll open another one for the initramfs issue if it turns out to be related to nitro. Thank you for the help!
