### ISSUE TITLE
outdated comments in nitro-enclaves-allocator

### ISSUE THREAD

**Issue by olafhering** [aws/aws-nitro-enclaves-cli#353]
My copy of `nitro-enclaves-allocator` has outdated comments at the beginning of the file.

I think `/etc/ne_mem` etc. are from the early days, the configuration moved to `/etc/nitro_enclaves/allocator.yaml`

**Comment by andraprs** [comment]
Here it is the fix: https://github.com/aws/aws-nitro-enclaves-cli/pull/354.

Thank you.
