### ISSUE TITLE
Enclaves failing to start. `--attach_console` argument should be optional

### ISSUE THREAD

**Issue by jakekgrog** [aws/aws-nitro-enclaves-cli#368]
The `--attach_console` flag was added in the latest release but has broken our builds as it wasn't optional 
https://github.com/aws/aws-nitro-enclaves-cli/blob/cdfa323f69a0cfff2204a25363c7334777c133d7/src/common/commands_parser.rs#L32

**Comment by petreeftime** [comment]
Hi @jakekgrog, can you describe the issue in more detail? I ran a few tests and the enclaves seem to start just fine without `--attach-console` flag in either debug or production mode on release 1.2.0.

**Comment by petreeftime** [comment]
There is no need for Optional<bool> there, as this doesn't reflect in either the way the CLI interprets the flags or the way that flag is used later on.

**Comment by alcioa** [comment]
Released in 1.2.1
