### ISSUE TITLE
Build idles

### ISSUE THREAD

**Issue by leongross** [aws/aws-nitro-enclaves-cli#409]
For the latest main branch (119a182d83d9a8e50a437b8e756e7ac47e10f897) the build seems to idle.
After running `make --verbose` the build stays in an idle like state.
No build artifacts seem to be produced.

```
[~/aws-nitro-enclaves-cli]$ make --debug                                                                               
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Updating makefiles....
Updating goal targets....
 File 'nitro-cli' does not exist.
   File 'build-setup' does not exist.
     File 'build' does not exist.
    Must remake target 'build'.
mkdir -p ./build
    Successfully remade target file 'build'.
  Must remake target 'build-setup'.
  Successfully remade target file 'build-setup'.
   File 'build-container' does not exist.
  Must remake target 'build-container'.
```

**Comment by petreeftime** [comment]
It's unlikely that the build idles, but I've changed the behavior of the build system with this commit: https://github.com/aws/aws-nitro-enclaves-cli/commit/cc7062329aada61b182fbe9934411b8c66e74efa. It takes a long time to produce the nitro_cli container and now it doesn't log too much of the process.

**Comment by petreeftime** [comment]
Ideally you wouldn't have to use `make`, `cargo` should just work and it doesn't need so many things.

**Comment by leongross** [comment]
> Ideally you wouldn't have to use `make`, `cargo` should just work and it doesn't need so many things.

**Comment by leongross** [comment]
> Ideally you wouldn't have to use `make`, `cargo` should just work and it doesn't need so many things.
I followed [this](https://github.com/aws/aws-nitro-enclaves-nsm-api/tree/main/nsm-test) guide to run the tests. [There](https://github.com/aws/aws-nitro-enclaves-nsm-api/blob/main/Makefile#L60) the make targets `.build-nsm-test-cpp-eif` -> `.build-nsm-test-cpp-docker` -> `command-executer-build` are invoked, which itself clones this repo and executes the `command-executer` target, so just using cargo is not an option.

**Comment by leongross** [comment]
> Ideally you wouldn't have to use make, cargo should just work and it doesn't need so many things.

I followed [this](https://github.com/aws/aws-nitro-enclaves-nsm-api/tree/main/nsm-test) guide to run the tests. [There](https://github.com/aws/aws-nitro-enclaves-nsm-api/blob/main/Makefile#L60) the make targets `.build-nsm-test-cpp-eif` -> `.build-nsm-test-cpp-docker` -> `command-executer-build` are invoked, which itself clones this repo and executes the `command-executer` target, so just using cargo is not an option.
