### ISSUE TITLE
Periodic ioctl failures when starting the enclave

### ISSUE THREAD

**Issue by nshyrei** [aws/aws-nitro-enclaves-cli#433]
Sometimes when starting the enclave immediately after the previous one exits I get the following ioctl failure:
```
[ E29 ] Ioctl failure. Such error is used as a general ioctl error and appears whenever an ioctl fails. In this case, the error backtrace provides detailed information on what specifically failed during the ioctl.

For more details, please visit https://docs.aws.amazon.com/enclaves/latest/user/cli-errors.html#E29

If you open a support ticket, please provide the error log found at "/var/log/nitro_enclaves/err2022-12-13T10:02:00.293684260+00:00.log"
Failed connections: 1
[ E39 ] Enclave process connection failure. Such error appears when the enclave manager fails to connect to at least one enclave process for retrieving the description information.

For more details, please visit https://docs.aws.amazon.com/enclaves/latest/user/cli-errors.html#E39

If you open a support ticket, please provide the error log found at "/var/log/nitro_enclaves/err2022-12-13T10:02:00.294701692+00:00.log"
```

The issue solves itself by retrying `nitro-cli start-enclave` or by restarting the `allocator` service.

**Comment by andraprs** [comment]
Thank you for the shared details.

Can you please also add to the GitHub issue the content from the error log file e.g. "/var/log/nitro_enclaves/err2022-12-13T10:02:00.293684260+00:00.log", if you still have it. It would be helpful to check out and see if there are additional details on the ioctl failure.

Thank you.

**Comment by alcioa** [comment]
@nshyrei what is the latest status here on your end? Running enclave run/terminate in a loop does not yield such behavior.

**Comment by nshyrei** [comment]
@alcioa Yes, this is still happening. Can you please elaborate further a little bit, I didn't understand. I am starting the enclave afte my application terminates the previous enclave.

**Comment by nshyrei** [comment]
Finally figured, it was because of another process trying to start an enclave on my machine
