### ISSUE TITLE
Standalone NSM Driver

### ISSUE THREAD

**Issue by ReillyBrogan** [aws/aws-nitro-enclaves-cli#576]
Hello, I just read about the NSM driver being added to char-misc-next for inclusion in kernel 6.8. Are there any plans to provide a standalone version of the kernel module that users of prior stable kernels can build and use? Such as how the ENA driver is available, or how the rest of the Nitro Enclave driver is available in this repo. 

Given how most server distros stick to LTS kernels it otherwise wouldn't be until the end of the year when the driver would be readily available to most users.

**Comment by Cottand** [comment]
Hi @meerd please do not close this issue
- it is still not clear how to reproduce a NSM build for any kernels other than the one in `/blobs`
- there are no examples of how to use any other kernels other than the one in `/blobs`, with or without an NSM build compiled by a customer
- there are no examples of how to use Kernel 6.8+ with Nitro enclaves, even though the NSM module is now in-tree
