### ISSUE TITLE
bogus tag for bc9c0b8

### ISSUE THREAD

**Issue by olafhering** [aws/aws-nitro-enclaves-cli#603]
Please remove the bogus tag `v.1.2.3` with the extra dot from the repository.
This bogus tag breaks external tooling because the commit has two tags. The tooling can not decide which one to chose, and promptly selects the bogus tag:

````
git log '--pretty=format:%H %G? %h %D' "--topo-order"
...
bc9c0b8362287698c0348ffd1df1fcaa9f0ccce3 N bc9c0b8 tag: v1.2.3, tag: v.1.2.3
...
````

https://github.com/openSUSE/obs-service-tar_scm/blob/9df35c1/TarSCM/scm/git.py#L594

Thank you.

**Comment by olafhering** [comment]
Well, the actual command to show the bogosity is `git describe --tags --abbrev=0`.

**Comment by meerd** [comment]
Thanks for the heads-up @olafhering. The bogus tag has been removed.
