### ISSUE TITLE
`vsock-proxy` DNS lookup fails inside VPC with no internet access.

### ISSUE THREAD

**Issue by rohan-passbird** [aws/aws-nitro-enclaves-cli#623]
Recent changes to the `vsock-proxy` code use a different DNS resolver that uses Google's DNS servers by default(https://github.com/aws/aws-nitro-enclaves-cli/blob/main/vsock_proxy/src/dns.rs#L56). This fails when an EC2 machine runs in a subnet with no internet access.

**Comment by rohan-passbird** [comment]
Here's the link to the DNS resolver default config that's being used currently: https://github.com/hickory-dns/hickory-dns/blob/f1489da675c21fddc189f2c9505bc9da6c156835/crates/resolver/src/config.rs#L313

**Comment by meerd** [comment]
Hello @rohan-passbird,

This is a known issue and will be resolved with this [PR622](https://github.com/aws/aws-nitro-enclaves-cli/pull/622).

**Comment by rohan-passbird** [comment]
Got it. Thanks!

**Comment by meerd** [comment]
The latest release, [v1.3.1](https://github.com/aws/aws-nitro-enclaves-cli/releases/tag/v1.3.1), resolves the issue. In approximately two weeks, the RPM package should be available in the Amazon Linux repositories.

**Comment by jplock** [comment]
Amazon Linux 2023.5.20240624 includes this fix

https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.5.20240624.html
