### ISSUE TITLE
Is it possible to build an enclave in a running enclave?

### ISSUE THREAD

**Issue by zensh** [aws/aws-nitro-enclaves-cli#634]

**Comment by foersleo** [comment]
Hi @zensh,

Could you elaborate a little bit on what you want to do?
Are you talking about creating enclave image files from within an enclave?

**Comment by zensh** [comment]
> Hi @zensh,
> 
> Could you elaborate a little bit on what you want to do? Are you talking about creating enclave image files from within an enclave?

Yes! I hope to build other enclave images in a trusted enclave container.
